apiVersion: apps/v1
kind: Deployment
metadata:
   name: application

spec:
   selector:
     matchLabels:
        app: app1
   template:
     metadata:
        labels:
          app: app1
     spec:
       containers:
           - image: httpd:latest
             name: app1
             volumeMounts:
                - mountPath: "/usr/local/apache2/htdocs/"
                  name: index
       volumes:
          - name: index
            hostPath:
               path: /home/kubernetes
               type: DirectoryOrCreate
